# Conda environment for the Unified Drug Discovery Analysis Platform
# To create: conda env create -f environment.yml
name: uddap_env
channels:
  - conda-forge
dependencies:
  # --- Core & Web App---
  - python=3.10
  - streamlit
  - pip

  # --- Data Science & ML ---
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - pytorch
  - gpytorch
  - cpuonly # IMPORTANT: Keep for Streamlit Cloud deployment unless GPU is specified.
  
  # --- Visualization ---
  - matplotlib
  - seaborn
  - plotly
  
  # --- Cheminformatics ---
  - rdkit
  
  # --- Explainable AI (XAI) ---
  - shap

  # --- Optional Packages ---
  - umap-learn
  - transformers
