name: shap-analysis
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - rdkit
  - streamlit
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - scipy
  - pillow
  - pytorch::pytorch
  - pytorch::cpuonly
  - pip
  - pip:
    - gpytorch
    - shap
